import "./globals.css";


import type { Metadata } from "next";
import { Audiowide } from "next/font/google";

const AudioW = Audiowide({
  weight: "400",
  subsets: ["latin"],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${AudioW.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
